language: python
python:
  - "2.6"
  - "2.7"
install:
  - "pip install pytest --use-mirrors"
  - "pip install . --use-mirrors"  
  - "pip install -r requirements.txt --use-mirrors"
script:
  - sh -c 'cd src && python tests/runtests.py -v'